export const MessageEnum = {
  error: {
    USER_CREATED: 'User created successfully.',
    USER_NOT_FOUND: 'User not found.',
    EMAIL_EXISTS: 'Email already exists.',
    ACCESS_DENIED: 'Access denied.',
    INVALID_REFRESH_TOKEN: 'Refresh token invalid.',
    INVALID_CREDENTIALS: 'Invalid credentials.',
    NOT_FOUND: 'Resource not found.',
    SERVER_ERROR: 'Internal server error.',
    CARD_ATTACHED_SUCCESSFULLY: 'Card attached successfully.',
    PAYMENT_INTENT_CONFIRMED: 'PaymentIntent confirmed.',
    PAYMENT_REFUNDED: 'Refund payment successfully.',
    PAYMENT_MIN_AMOUNT: 'Minimum charge for JOD is 200 fils (0.200 JOD).',
    PAYMENT_NO_CUSTOMER: "PaymentIntent has no customer",
    PAYMENT_NO_USER: "No user found for this Stripe customer",
    NO_REFRESH_TOKEN_PROVIDED: 'No refresh token provided.',
    WEBHOOK_SIGNATURE_FAILED: 'Webhook signature verification failed.',
  },
  swaggerExample: {
    EMAIL: "john@example.com",
    PASSWORD: "StrongPass@123",
    NAME: 'John Doe',
    PAYMENT_METHOD_ID: "pm_card_visa",
    DECLINED_PAYMENT_METHOD_ID: "pm_card_chargeDeclined",
    CUSTOMER_ID: "cus_TWaXQkywA4RZrO",
    PAYMENT_INTENT_ID: "pi_3Ox12345ABCxyz",
    AMOUNT: 1000,
    MIN_AMOUNT: 200,
    CURRENCY: "jod",
    DEFAULT_CURRENCY: "usd",
    VALIDATION: {
      NAME_MIN_LENGTH: 'Name must be at least 2 characters long',
      NAME_MAX_LENGTH: 'Name must be less than 50 characters',
      EMAIL: "Invalid email format",
      PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long',
      PASSWORD_MAX_LENGTH: 'Password must be less than 100 characters',
      PASSWORD_UPPERCASE: 'Password must contain at least one uppercase letter',
      PASSWORD_LOWERCASE: 'Password must contain at least one lowercase letter',
      PASSWORD_NUMBER: 'Password must contain at least one number',
      PASSWORD_SPECIAL_CHAR: 'Password must contain at least one special character (@$!%*?&)',
      AMOUNT_MIN_LENGTH: 'Amount must be at least 200',
    }
  },
};
